### ISSUE TITLE
brain-dump 1

### ISSUE THREAD

**Issue by klemens-morgenstern** [Felspar/coro#1]
I have a bunch of unordered thoughts on what I would want to have, so it's not too refined and not complete either.

I don't know if it's a fit, but I basically want reactive programming, where an action pushed a value through a stack of coroutines top to bottom. 
 The basic idea is to make it easy to throw a bunch of asio thingies together  and build a stream from it.

1. Allocators

This works by matching the coro argument list to the promise, and using `std::allocator_arg` somewhere in the argument list of a coro type.

```cpp
template<typename Executor, typename Allocator>
struct promise_frame_base_allocator : promise_frame_base<Executor>
{

    template<typename Class, typename Exec_, typename ... Args>
    void* operator new(std::size_t size, Class&&, Exec_ &&, std::allocator_arg_t, const Allocator & allocator, Args&&...)
    {
        return _new_impl(size, allocator);
    }

    template<typename Exec_, typename ... Args>
    void* operator new(std::size_t size, Exec_ &&, std::allocator_arg_t, const Allocator & allocator, Args&&...)
    {
        return _new_impl(size, allocator);
    }

    template<typename ... Args>
        requires (not std::convertible_to<Args, std::allocator_arg_t> && ...)

    void* operator new(std::size_t size, Args && ...)
    {
        return _new_impl(size, Allocator());
    }

    void operator delete(void * ptr, std::size_t size)
    {
        constexpr auto al = alignof(Allocator);
        std::size_t size_rounded_to_alignment =
            ((size % al) > 0)
            ? (size + (al - (size % al)))
            : size;

        std::size_t allocator_offset = size_rounded_to_alignment;
        void* a = static_cast<char*>(ptr) + allocator_offset;
        Allocator &alloc = std::move(*static_cast<Allocator*>(a));

        Allocator alloc_copy = alloc;
        alloc.~Allocator();
        alloc_copy.deallocate(allocator_offset + sizeof(Allocator));
    }

    using allocator_type = Allocator;
  private:

    static void* _new_impl(std::size_t size, const Allocator & allocator)
    {
        constexpr auto al = alignof(Allocator);
        std::size_t size_rounded_to_alignment =
            ((size % al) > 0)
            ? (size + (al - (size % al)))
            : size;

        std::size_t allocator_offset = size_rounded_to_alignment;
        Allocator alloc = allocator;

        void *ptr = allocator.allocate(allocator_offset + sizeof(Allocator));
        new (static_cast<char*>(ptr) + allocator_offset) Allocator(std::move(alloc));
        return ptr;
    }

};

//this should probably us an allocator_trait instead
template<typename Executor>
struct promise_frame_base_allocator<Executor, std::allocator<void>> : promise_frame_base<Executor>
{
    template<typename ... Args>
    promise_frame_base_allocator(Args && ...args) : promise_frame_base<Executor>(std::forward<Args>(args)...) {}

    auto await_transform(this_coro::allocator_t) noexcept
    {
        return detail::co_await_getter{[this]{return get_allocator();}};
    }

    using allocator_type = std::allocator<char>;
    allocator_type get_allocator() {return std::allocator<char>{};}
};
```

Additonally one could check if a given input parameter has a `get_allocator` function and then propagate it like so:

```cpp
stream<int> foo(stream<int> s); //will use s.get_allocator()
```

The massive disadvantage of that is that this would propagate the `vector` allocator:

```cpp
stream<int> foo(std::vector<int>)_;
```

2. Integration into asio.

Basically what I want is a promise type that has two things; wait for next value & cancel operation. Now currently (I talked to Chris, he said he'd be open to adding that option to asio) this isn't possible, but what we could do is something like this:

```cpp
promise<void> tick(asio::steady_timer & st)
{
     return  st.async_wait(use_promise([&]{st.cancel();});
}
```

Basically this means that a promise should be able to be able to be used as a callback+cancel.

3. Cancellation

Cancellation should propagate upwards through a stack of promises/streams:

```cpp
promise<void> first()
{
   auto tick = [](asio::steady_timer & st) -> promise<void> 
  {
     return  st.async_wait(use_promise([&]{st.cancel();});
   };
   asio::steady_timer st;
   co_await tick(st);
}


auto f= first();
f.cancel(); //cancels the timer
```

4. Exceptions & Errors

I would like exceptions to be optional, every coro type should have a `Error` type parameter. If it's a `std::exception_ptr` it's an exception, otherwise a value. These value should however be propagated:

```cpp
promise<int, error_code> p
{
    co_await [] () -> promise<int, error_code>
    {
        co_return error_code(42); //cancel the stack of promises
    }();
    //never gets called
}
```

4. Streams

So from my perspective a stream is like a promise that can also yield values, so it has three (main) parameter types :

1. Yield
2. Return
3. Error 

For an expression of `co_await stream` I would propose the following type deductions:

| Yield | Return| await
|-------|--------|-------|
| T | void | optional<T> |
| void | U | variant<monostate, U> |
| T | U | variant<T, U> | 

5. asio again

While it makes perfect sense to have `co_await stream/promise` within a coro, I would also like to have a non-coro interface for a stream. I would model it after asio, i.e. have a `async_wait((T, U, Error) =>)` and cancel member function.

**Comment by KayEss** [comment]
Great to see your thoughts, thanks for the input.

These are just first impressions -- probably after a round or two of this we should split these into separate issues to make discussion and tracking a bit easier.

1. Is it only me who finds the `std::allocator_arg` really ugly? I think it would be neat to have a concept here as well that can be used, but I agree it's important to separate the coroutine stack allocator from one for other types or all sorts of bad things could happen. I have a design for a slab like allocator for use in things like networking and parsing which I'll try to write up at some point.
2. I was under the impression that ASIO already had some coroutine support, or does it still require something else to provide complete support?
3. Cancellation is not something I've given much thought to, but your idea looks sound.
4. (first 4) I don't know much about writing code in an environment where exceptions are not used. Is it enough to just not use them, or does the code have to be more explicit about things? I'd hate to have to add in a ton of conditional compilation support with `#ifdef` everywhere.
5. (second 4) There's a technical reason for the difference between a stream and generator -- the generator can be used from a non-coroutine, but it's implementation is restricted to only `co_yield`. For the stream the coroutine that generates the stream can use `co_await`, but this means they can also only be used from coroutines as the next value must be `co_await`ed in turn. Like the generator, the streams here don't `co_return` values as there's no clear way to get at them (although I think a suitable API is maybe clearer in the stream case, but only maybe...). I think a stream that doesn't `co_yield` is just a task.
6. (your 5) This sounds interesting. It would be good to have another way to interface between coroutines and normal functions. I guess a callback like thing could work -- I'd have to think about this

**Comment by klemens-morgenstern** [comment]
1. It is incredibly ugly. Implicit contextualization is however less acceptable. We could introduce an `allocator` concept and the just take that when passed in, instead of the tag. 

2. It does, but it is incredibly fenced off. Which I get, but all you get is a lazy promise - since it's lazy you don't have cancellation
4. a `throw` in compiled code will yield an error. But this can be wrapped in a `throw_X` function that calls terminate with exceptions disabled.
5. In theory we could make a stream do both, IF the ultimate worker object (e.g. the timer) has a sync function. So instead of calling wait or async_wait the coro picks depending on whether it was called with wait or async_wait. To me this seems like a lot of complexity for no real benefit, since I am only using this on asio, but it would be an option. Overhead shouldn't be too bad.

```
promise<void> foo() { co_await promisify(timer); };


foo.wait(); // --> timer.wait()
foo.async_wait(); // --> timer.async_wait()
foo.cancel(); //--> timer.cancel()
```

Then, there wouldn't be a difference between generator & stream.

6. Well I would just use `asio::async_completion` for that.

**Comment by KayEss** [comment]
I've been thinking about this, and I was thinking that the exception stuff should be clear enough to start to draw up a bit more of a plan, but the problem with it is that if we want to be able to run tests of a non-exception version (and I'm pretty sure we do) then the test library has to support no exceptions first, which is a bit more difficult. The test library uses exceptions to report test failures so I'll have to think about what a non-exception API might look like, and the problem is the `if` statements that would be required -- which ironically could be turned into `co_await` if we were to mix the coroutines in

**Comment by klemens-morgenstern** [comment]
I don't think I get the problem with the test library, but imo we'd be fine to define the error-type and default it to `std::exception_ptr` for the time being. I just would like the no-except version to be possible later on. 

As far as I played with coros so far, you're most likely gonna put the exception into an exception_ptr anyhow and then rethrow it, so I don't think it would be *that* different for another type.

**Comment by klemens-morgenstern** [comment]
Oh another issue: stacking coros, is one I have thought about. boost.asio is doing this by having a "thread" which works like a linked list. `co_await` will cause the `awaitable` to be pushed on top of the list and the thread you executed just calls `resume` on the top one until the stack is empty. That does work, but we could also do another thing: call the next coroutine in `await_ready` and then suspend if it suspends or just continue without suspension if it completes.

**Comment by klemens-morgenstern** [comment]
Never mind the last commentary, MSVC doesn't implement that correctly. The correct solution is the return the callee coro_handle from the initial `await_suspend` and the one of the caller in the `await_suspend` in the `final_suspend`.

**Comment by KayEss** [comment]
I've started work on an IO library now, which is at https://github.com/Felspar/io I'm about to land a PR that will make exceptions from IO optional (at the cost of a small amount of extra syntax). I think a similar thing could be done here so that exceptions wouldn't have to be thrown at a co_await etc. and an overload of co_return would allow exceptions to be returned as error values. It's not a great way because examining exceptions isn't very easy without an ability to throw them, but at least their presence can be detected without breaking compatibility with the core language.

Oh, and allocators are now a thing, but probably also need refining a little more

**Comment by KayEss** [comment]
The IO library now has optional exceptions and allocators are supported here.
