### ISSUE TITLE
'int felspar::coro::task<int,void>::get(void) &': attempting to reference a deleted function

### ISSUE THREAD

**Issue by chenscottus** [Felspar/coro#3]
Hello,

   When I implement a function:

      `felspar::coro::task<int>`  read_frames(){ ...};// please ignore `, without, `<int>` cannot show up here
      ...
      `felspar::coro::task<int>` result = read_frames(); // please ignore `, without, `<int>` cannot show up here
      ...
      result.get();

   result.get() fails and the error message:
     'int felspar::coro::task<int,void>::get(void) &': attempting to reference a deleted function

   please help.

   Thanks!

-Scott

**Comment by KayEss** [comment]
Hii, because `get` consumes the result it takes an r-value, so you should use either `read_frames(XXX).get()` directly or, if you need to do it later on then, `std::move(result).get()`

**Comment by KayEss** [comment]
I've added some extra information to the readme to explain this aspect of the API. Hopefully that would have answered your question directly.

**Comment by chenscottus** [comment]
Thanks!

let me try it and find out if there is any problem or not.

**Comment by chenscottus** [comment]
When the state of result is "handle=myapp!read_frames(void*)#initial suspend", I use std::move(result).get(), no problem.

When the state of result is "handle={Promise{value{=-57266307}}}} " , I use std::move(result).get(), I got exception.
coro\include\felspar\coro\task.hpp, line 80, check_exception();

I have checked, the value.has_value() is true.

If I remove line 80, check_exception();, even the program continue, but I always get the first value ...

Please help.

Thanks!

**Comment by KayEss** [comment]
If there's an exception whilst your coroutine runs then `.get()` is meant to throw it. `has_value` is true if either there is an exception or if the value has been returned.

It sounds like you have an exception during execution of the code. What is the exception you're seeing and can you tell if it relates to what your code is doing?

**Comment by chenscottus** [comment]
It should be the local variable out of scope.

How can I do this:
   `felspar::coro::task<int>` result;
   //Do somethings
   {
         result = read_frames();
         //Do somethings
   }
   //Do somethings
   std::move(result).get() //wait for read_frame to finish
   //Do somethings

Thanks!

**Comment by KayEss** [comment]
The first thing to understand is that the task won't be started until you either `co_await` it or you `.get()` it. They start lazily. If you need to start coroutines eagerly you can use [`starter<felspar::coro::task<int>>`](https://github.com/Felspar/coro/blob/main/include/felspar/coro/start.hpp). There are two consequences there though -- firstly the implement and design aren't fully baked yet (the implementation is not yet exception safe) and secondly you lose access to the return value.

**Comment by KayEss** [comment]
Did you manage to sort your problem out?

**Comment by chenscottus** [comment]
I thought coroutines should be different very simple thread  comparing the main thread.  Have to support multi-threads to boost the performance about reading images, processing images, streaming images, and saving images.  so I turn out to use thread-pool. It did do the job!

**Comment by chenscottus** [comment]
The problem should be out of scope. I had to declare the variable first, and initialize later, and use it somewhere.

**Comment by KayEss** [comment]
If you are CPU bound then coroutines will only make matters worse. They really shine for IO bound tasks where a thread would otherwise be sleeping a lot can service other IO instead.
